version: '3'

services:
  
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
        - jenkins-service
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80

  jenkins-service:
    image: istresearch/jenkins:latest
    container_name: jenkins-service
    user: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_HOST_HOME: "./jenkins"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
